### ISSUE TITLE
Tooltip should stand out in dark theme

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#96] opened 2015-03-03 23:42 UTC
The background of the tooltip is the same as the content's background, that makes the tooltip not fade in with the content, and makes the tooltip's arrow invisible.
Maybe #222 as background ?

**Comment by PalmerAL** [comment] 2015-03-03 23:43
duplicate of #51

**Closed by PalmerAL** 2015-03-03 23:43 UTC

**Comment by nt1m** [comment] 2015-03-03 23:47
Whoops, completely forgot I filed it earlier
