### ISSUE TITLE
Starring paragraphs doesn't work

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#72] opened 2015-02-27 00:16 UTC
I use Firefox

**Comment by PalmerAL** [comment] 2015-02-27 20:48
This is because firefox just adds br tags instead of actually creating paragraphs. What do you think the solution to this is?

**Comment by PalmerAL** [comment] 2015-02-27 22:09
I switched this to allowing anything to be starred. this doesn't help in most cases, though, because the text is usually not wrapped in any tag.

**Comment by nt1m** [comment] 2015-02-27 23:30
@PalmerAL I should have clarified, it does show the star, but clicking on it doesnt do anything

**Comment by nt1m** [comment] 2015-02-27 23:31
Maybe that's just for newly created p

**Comment by PalmerAL** [comment] 2015-02-28 04:38
Hmmm... This should work correctly. Is there anything in the console?

**Comment by nt1m** [comment] 2015-02-28 07:25
That's the scary part, no. But things might have changed though, but i wont have time to test (at least not today)

**Comment by PalmerAL** [comment] 2015-03-01 22:33
Also, headings have an issue where clicking the very right edge of the star doesn't work.

**Comment by PalmerAL** [comment] 2015-05-31 23:22
Closing for now as WFM. If you can reproduce again, please reopen.

**Closed by PalmerAL** 2015-05-31 23:22 UTC
