### ISSUE TITLE
Header is sometimes white on dark theme

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/scratchpad#113] opened 2015-03-07 20:57 UTC
I can't reproduce often.

**Comment by PalmerAL** [comment] 2015-03-07 21:12
Which header?

**Comment by nt1m** [comment] 2015-03-07 21:17
Editor header

**Comment by PalmerAL** [comment] 2015-04-18 17:30
I guess I'll go ahead and close this for now, since there aren't steps to reproduce. This sounds a lot like a browser bug - the darktheme just adds and removes a class from the body, so the results should be the same every time.

**Closed by PalmerAL** 2015-04-18 17:30 UTC
